# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

###
### Primary keybinds
###

# close active window
# bind = $mainMod, Q, killactive
bind = $mainMod, Q, exec, ~/.config/hypr/scripts/kill-window.sh
# options to logout, reboot, shutdown, etc
bind = $mainMod SHIFT, Q, exec, wlogout
# lock session
bind = $mainMod, escape, exec, hyprlock
# reload hyprland
bind = $mainMod SHIFT, R, exec, ~/.config/hypr/scripts/reload.sh
# toggle floating/tiling for active window
bind = $mainMod, V, togglefloating
# toggle fullscreen for active window
bind = $mainMod, M, fullscreen
# application launcher menu
bind = $mainMod, R, exec, rofi -show drun
# emoji picker
bind = $mainMod, period, exec, rofi -modi emoji -show emoji

###
### App launcher bindings
###

# terminal
bind = $mainMod, Return, exec, kitty

# keybind to "apps" submap
bind = $mainMod, A, submap, apps

# begin configuration of apps submappings
submap = apps

# launchers for my most commonly used apps
bind = , F, exec, thunar # file manager
bind = , B, exec, firefox # browser
bind = , P, exec, firefox --private-window # private browser
bind = , E, exec, thunderbird # email
bind = , N, exec, obsidian # notes

# exit submap with any keypress, including launching an app
bind=,catchall,submap,reset

# end configuration of apps submappings
submap = reset

###
### Special keyboard keys
###

# Screen brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Volume and Media Control
bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindel = , XF86AudioLowerVolume, exec, pamixer -d 5
bindl = , XF86AudioMute, exec, pamixer -t
bind = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPause, exec, playerctl play-pause

# TODO:
# external monitor button (f8)
# calculator buttons (launcher and "CE")

###
### Window/Workspace management
###

# Special (scratchpad) workspace
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Move focus with mainMod + vim directions
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Move active window with mainMod + SHIFT + vim directions
bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, L, swapwindow, r
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, J, swapwindow, d

# Resize active window with mainMod + Alt + vim directions
bind = $mainMod ALT, H, resizeactive, -20 0
bind = $mainMod ALT, L, resizeactive, 20 0
bind = $mainMod ALT, K, resizeactive, 0 -20
bind = $mainMod ALT, J, resizeactive, 0 20

# Switch workspaces with mainMod + [1-0(ten)]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
