exec-once = swww init
exec-once = ~/.config/hypr/scripts/swww-random.sh ~/pictures/wallpapers/
exec-once = waybar
exec-once = dunst
exec-once = hypridle
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = udiskie &
exec-once = nm-applet &
exec-once = blueman-applet &
