# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-1,2560x1440@164.83,0x0,1
monitor=HDMI-A-1,1920x1080@60,2560x360,1 # place to right of DP-1, aligned at bottom

# Startup
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/windowrules.conf

