# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,1920x1080@60,0x0,1
monitor=,preferred,auto,1

# Startup
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/windowrules.conf

