# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
general {
  gaps_in = 2
  gaps_out = 2
  border_size = 3
  col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  col.inactive_border = rgba(595959aa)
  layout = dwindle
  resize_on_border = true

# Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
  allow_tearing = false
}

cursor {
  inactive_timeout = 10
}

decoration {
  rounding = 2
  drop_shadow = false # nice, but turned off to save battery
  # shadow_range = 4
  # shadow_render_power = 3
  # col.shadow = rgba(1a1a1aee)

  blur {
    enabled = true
    size = 3
    passes = 1
  }
}

animations {
  enabled = yes

# Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

  bezier = myBezier, 0.05, 0.9, 0.1, 1.05

  animation = windows, 1, 7, myBezier
  animation = windowsOut, 1, 7, default, popin 80%
  animation = border, 1, 10, default
  animation = borderangle, 1, 8, default
  animation = fade, 1, 7, default
  animation = workspaces, 1, 6, default
}

input {
  # swap left control key with caps-lock
  kb_options = ctrl:swapcaps

  numlock_by_default = true
  follow_mouse = 2

  touchpad {
    natural_scroll = no
    tap-to-click = true
    drag_lock = true
    tap-and-drag = true
  }

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

gestures {
  workspace_swipe = true
}

misc {
  disable_hyprland_logo = true
  force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
  vfr = true # battery saver
}

dwindle {
# master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  pseudotile = true # false 

  preserve_split = yes # you probably want this

# Gap options when only one window in a workspace
# 0: disabled. Use gaps and border
# 1: no gap & no border
# 2: no gap with border
  no_gaps_when_only = 1 # 0

# Force split - Open new split direction
# 0: split follows mouse
# 1: always split to the left/top
# 2: always split to the right/bottom
  force_split = 2 # 0

# if enabled, resizing direction will be determined by the mouse’s position on the window (nearest to which corner). Else, it is based on the window’s tiling position
  smart_resizing = false # true
}

master {
# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  new_is_master = false
# Gap options when only one window in a workspace
# 0: (default) disabled. Use gaps and border
# 1: no border
# 2: with border
  no_gaps_when_only = 1
# master split factor. [0.0 - 1.0] default 0.55
  mfact = 0.50
}

